spring.application.name=mini_10

# data source
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mini_10
spring.datasource.username=root
spring.datasource.password=1234

# session persistence
server.servlet.session.persistent=false

# jpa
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# junit test logging
logging.level.root=info
logging.level.com.mycom.myapp=DEBUG

logging.level.org.hibernate.orm.jdbc.bind=TRACE

# jwt secret key
myapp.jwt.secret=sdfasd9023rasdkfjasfdqw3fw34fasdfasfasdfasfef3w3f